### ISSUE TITLE
Issue in 'appendFormat'?

### ISSUE THREAD

**Issue by jgmdavies** [toomasz/ArduinoFixedString#2]
Very impressive!  Just at the right time for me, as I scratch my head again with overrunning 'char arrays' somewhere...

Your test output shows:
   `content: '10 20 3' length: 8, free = 0`

Shouldn't it be:
   `content: '10 20 30' length: 8, free = 0`

as the underlying char has space for the 8 characters + null?

I think a possible fix is to change the line:
   `auto addedCharacters = vsnprintf(_string + _length, remainingSpace, format, argptr);`
in 'appendFormat' to:
   `auto addedCharacters = vsnprintf(_string + _length, remainingSpace + 1, format, argptr);`

as 'vsnprintf' expects the -total- buffer size (i.e. including the null) in the second arg?

Best wishes, and thanks,
Jim

**Comment by toomasz** [comment]
Jim,
Thanks for reporting the issue. I have fixed it according to your suggestion and also made appendFormat consistent with other methods(return bool, dont append anything if not space available)

**Comment by jgmdavies** [comment]
Thanks Tomasz, that's great.

By the way, I'm using this successfully in a C++ 'Windows Console Application' in VS2017, and so far the only change I've needed is to change to:

```
#ifdef ARDUINO
	#include <Arduino.h>
#endif
```

near the top of FixedString.h.
I'm not using normal C++ Strings because I'm developing Arduino code and (i) I don't want to use Strings for the Arduino, and (2) I prefer to develop in Visual Micro in VS2017.  I use a C++ 'Windows Console Application' with as much of the same code as possible (and several #ifdefs), so I can debug easily in VS and interact more 'richly'!

Jim

**Comment by toomasz** [comment]
Probably #include<string.h> would suffice but i was getting weird errors when incuding it, thats why arduino.h was used.

Actually I develop with Visual micro as well but im not very happy with it. It's hard to make it work properly when multi project solution is used.

**Comment by jgmdavies** [comment]
Thanks Tomasz.

 

What problems do you get with multi-project solutions?  I think most of mine have been single-project solutions so far.
