### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by bblanchon** [toomasz/ArduinoFixedString#4]
Hi, 

I just saw that the link to "What is heap fragmentation" is dead.
The new location is https://blog.quasardb.net/2009/07/05/what-is-heap-fragmentation

BTW, I did myself write an article on the topic, and I think it's more accessible to your users than the article from Edouard Alligand.
Here it is: https://cpp4arduino.com/2018/11/06/what-is-heap-fragmentation.html

Regards,
Benoit

**Comment by toomasz** [comment]
Thanks for finding that out.
I have linked your article in readme, its great!
